spring:
  application:
    name: vrooms
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOLE_CLIENT_ID}
            client-secret: ${GOOLE_CLIENT_SECRET}
            scope: profile, email
  data:
    mongodb:
      database: vrooms
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:vrooms-self-signed.p12
    key-store-type: PKCS12
    key-store-provider: SUN
    key-store-password: vrooms

cors:
  allowed:
    origins: http://localhost:4200
    methods: GET, POST, PUT, DELETE, OPTIONS

openvidu:
  url: https://localhost:4443/
  secret: MY_SECRET
  publicurl: local

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /api-docs
    oauth:
      app-name: vrooms
      client-id: ${GOOLE_CLIENT_ID}
      client-secret: ${GOOLE_CLIENT_SECRET}

logging:
  level:
    org.springframework.web: debug
    io.vrooms: info
